export const DELETE_AUTH_INFO = 'DELETE_AUTH_INFO';
export const STORE_USER = "STORE_USER";
export const STORE_USER_SAGA = "STORE_USER_SAGA";
export const SET_OCCURRENCES_WITH_USERS = "SET_OCCURRENCES_WITH_USERS";
//userAccount
export const STORE_PROFILE_IMG_URL = "STORE_PROFILE_IMG_URL";
export const STORE_PROFILE_IMG_URL_SAGA = "STORE_PROFILE_IMG_URL_SAGA";
//events
export const SET_OCCURRENCES = "SET_OCCURRENCES";
export const FETCH_OCCURRENCES = "FETCH_OCCURRENCES";
export const PROCESS_EVENT_ATTENDANCE = "PROCESS_EVENT_ATTENDANCE";
export const SET_EVENT = "SET_EVENT";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const PROCESS_EVENT = "PROCESS_EVENT";
export const FETCH_USER_LIST = "FETCH_USER_LIST";

//authentication
export const SET_AUTH_INFO = "SET_AUTH_INFO";
export const LOG_USER_OUT = "LOG_USER_OUT";
export const UNSET_LOGGED_USER = "UNSET_LOGGED_USER";
export const LOGIN_USER = "LOGIN_USER";
