export const Create = 'Vytvoř';
export const First_Name = 'Jméno';
export const Last_Name = 'Přijímení';
export const PWD = 'Heslo';
export const First_Name_Limit = 'Jméno muže mít maximalně 16 znaků';
export const NICKNAME_LIMIT = 'Přezdívka muže mít maximalně 16 znaků';
export const BDAY_LIMIT = 'Maximálně 20 znaků'
export const Last_Name_Limit = 'Přijímení muže mít maximalně 16 znaků';
export const Invalid_Email = 'Neplatná emailová adresa';